backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
site_url: https://www.tokarta.com
logo_url: https://www.tokarta.com/img/tokarta-black.svg
collections:
  - name: "pages"
    label: "Pages"
    extension: json
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "english_posts"
    label: "Blog in English"
    folder: "_posts"
    create: true
    filter: { field: "language", value: "en" }
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "spanish_posts"
    label: "Blog en Español"
    folder: "_posts"
    create: true
    filter: { field: "language", value: "es" }
    fields:
      - {
          label: "Lenguaje",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
